#pragma once

#include <array>
#include <optional>
#include <string_view>

static constexpr std::array icons {// Peki <3
								   std::pair {u8"Peki", u8"\uf004 "},
								   std::pair {u8"peki", u8"\uf004 "},
								   // Programming
								   std::pair {u8"Android", u8"\ue70e "},
								   std::pair {u8"Atom", u8"\ue764 "},
								   std::pair {u8"C", u8"\ue61e "},
								   std::pair {u8"C#", u8"\uf81a "},
								   std::pair {u8"C++", u8"\ue61d "},
								   std::pair {u8"Eclipse", u8"\ue79e "},
								   std::pair {u8"Java", u8"\ue256 "},
								   std::pair {u8"LICENSE", u8"\ufae5"},
								   std::pair {u8"Makefile", u8"\ue615 "},
								   std::pair {u8"Python", u8"\ue235 "},
								   std::pair {u8"Tupfile", u8"\ue615 "},
								   std::pair {u8"android", u8"\ue70e "},
								   std::pair {u8"atom", u8"\ue764 "},
								   std::pair {u8"c", u8"\ue61e "},
								   std::pair {u8"c#", u8"\uf81a "},
								   std::pair {u8"c++", u8"\ue61d "},
								   std::pair {u8"cc", u8"\ue61d "},
								   std::pair {u8"gch", u8"\ue61d "},
								   std::pair {u8"class", u8"\ue256 "},
								   std::pair {u8"code", u8"\ufb0f "},
								   std::pair {u8"cpp", u8"\ue61d "},
								   std::pair {u8"cs", u8"\uf81a "},
								   std::pair {u8"css", u8"\ue749 "},
								   std::pair {u8"eclipse", u8"\ue79e "},
								   std::pair {u8"go", u8"\ufcd1 "},
								   std::pair {u8"h", u8"\ue61e "},
								   std::pair {u8"hh", u8"\ue61e "},
								   std::pair {u8"hpp", u8"\ue61d "},
								   std::pair {u8"htm", u8"\ue60e "},
								   std::pair {u8"html", u8"\ue736 "},
								   std::pair {u8"jar", u8"\ue256 "},
								   std::pair {u8"java", u8"\ue256 "},
								   std::pair {u8"js", u8"\ue74e "},
								   std::pair {u8"json", u8"\ue60b "},
								   std::pair {u8"lua", u8"\ue620 "},
								   std::pair {u8"make", u8"\ue615 "},
								   std::pair {u8"makefile", u8"\ue615 "},
								   std::pair {u8"mk", u8"\ue615 "},
								   std::pair {u8"o", u8"\ufc0c "},
								   std::pair {u8"out", u8"\ufc0c "},
								   std::pair {u8"pde", u8"\uf288 "},
								   std::pair {u8"php", u8"\uf81e "},
								   std::pair {u8"py", u8"\ue235 "},
								   std::pair {u8"pyc", u8"\ue73c "},
								   std::pair {u8"python", u8"\ue235 "},
								   std::pair {u8"script", u8"\uf977"},
								   std::pair {u8"scripts", u8"\uf977"},
								   std::pair {u8"sh", u8"\uf977"},
								   std::pair {u8"src", u8"\uf121 "},
								   std::pair {u8"tags", u8"\uf02b "},
								   std::pair {u8"ts", u8"\ue628 "},
								   std::pair {u8"tup", u8"\ue615 "},
								   std::pair {u8"vscode", u8"\ufb0f "},
								   std::pair {u8"wine", u8"\uf7a7 "},
								   std::pair {u8"yaml", u8"\ue73e "},
								   std::pair {u8"yml", u8"\ue73e "},
								   // Vim
								   std::pair {u8"nvim", u8"\ue62b "},
								   std::pair {u8"vi", u8"\ue62b "},
								   std::pair {u8"vim", u8"\ue62b "},
								   std::pair {u8"vimrc", u8"\ue62b "},
								   // Shh
								   std::pair {u8"emacs", u8"\uf044 "},
								   // Audio
								   std::pair {u8"mid", u8"\uf886 "},
								   std::pair {u8"midi", u8"\uf886 "},
								   std::pair {u8"mp3", u8"\ufc58 "},
								   std::pair {u8"m4a", u8"\ufc58 "},
								   std::pair {u8"mpa", u8"\ufc58 "},
								   std::pair {u8"Music", u8"\ufc58 "},
								   std::pair {u8"ogg", u8"\uf886 "},
								   std::pair {u8"wav", u8"\uf886 "},
								   std::pair {u8"wma", u8"\uf886 "},
								   // Video
								   std::pair {u8"avi", u8"\uf880 "},
								   std::pair {u8"h264", u8"\uf880 "},
								   std::pair {u8"m4v", u8"\uf880 "},
								   std::pair {u8"mkv", u8"\uf880 "},
								   std::pair {u8"mov", u8"\uf880 "},
								   std::pair {u8"mp4", u8"\uf880 "},
								   std::pair {u8"mpeg", u8"\uf880 "},
								   std::pair {u8"mpg", u8"\uf880 "},
								   std::pair {u8"Videos", u8"\uf880 "},
								   std::pair {u8"webm", u8"\ufa66"},
								   std::pair {u8"wmv", u8"\uf880 "},
								   // Image
								   std::pair {u8"bmp", u8"\uf7e8 "},
								   std::pair {u8"gif", u8"\uf952"},
								   std::pair {u8"jpg", u8"\uf1c5 "},
								   std::pair {u8"jpeg", u8"\uf1c5 "},
								   std::pair {u8"png", u8"\uf1c5 "},
								   std::pair {u8"Pictures", u8"\uf1c5 "},
								   std::pair {u8"ps", u8"\uf7ea "},
								   std::pair {u8"psd", u8"\ue7b8 "},
								   std::pair {u8"svg", u8"\ufc1f "},
								   std::pair {u8"tiff", u8"\ue60d "},
								   std::pair {u8"tif", u8"\ue60d "},
								   std::pair {u8"xcf", u8"\uf71e "},
								   // System Stuff
								   std::pair {u8"bak", u8"\ue615 "},
								   std::pair {u8"bashrc", u8"\ue615 "},
								   std::pair {u8"bash", u8"\ue615 "},
								   std::pair {u8"bin", u8"\uf114 "},
								   std::pair {u8"cfg", u8"\ue615 "},
								   std::pair {u8"conf", u8"\ue615 "},
								   std::pair {u8"config", u8"\ue615 "},
								   std::pair {u8"files", u8"\ue615 "},
								   std::pair {u8"includes", u8"\ue615 "},
								   std::pair {u8"creator", u8"\ue615 "},
								   std::pair {u8"dll", u8"\uf830 "},
								   std::pair {u8"firefox", u8"\ue745 "},
								   std::pair {u8"exe", u8"\ufab2"},
								   std::pair {u8"font", u8"\uf031 "},
								   std::pair {u8"fonts", u8"\uf031 "},
								   std::pair {u8"inf", u8"\uf7fc "},
								   std::pair {u8"info", u8"\uf7fc "},
								   std::pair {u8"ico", u8"\uf6f2 "},
								   std::pair {u8"icon", u8"\uf6f2 "},
								   std::pair {u8"icons", u8"\uf6f2 "},
								   std::pair {u8"ini", u8"\ue70f "},
								   std::pair {u8"lnk", u8"\ufab2"},
								   std::pair {u8"log", u8"\uf89d "},
								   std::pair {u8"msi", u8"\ufab2"},
								   std::pair {u8"sys", u8"\ue712 "},
								   std::pair {u8"temp", u8"\uf651 "},
								   std::pair {u8"tmp", u8"\uf651 "},
								   std::pair {u8"ttf", u8"\uf031 "},
								   std::pair {u8"eot", u8"\uf031 "},
								   std::pair {u8"otf", u8"\uf031 "},
								   std::pair {u8"woff", u8"\uf031 "},
								   std::pair {u8"xml", u8"\uf72d "},
								   std::pair {u8"zsh", u8"\ue615 "},
								   std::pair {u8"zsh_history", u8"\uf7d9 "},
								   std::pair {u8"zshrc", u8"\ue615 "},
								   // Office Stuff
								   std::pair {u8"csv", u8"\uf717 "},
								   std::pair {u8"doc", u8"\uf72c "},
								   std::pair {u8"docx", u8"\uf72c "},
								   std::pair {u8"latex", u8"\ue612 "},
								   std::pair {u8"md", u8"\ue609 "},
								   std::pair {u8"odp", u8"\uf1c4 "},
								   std::pair {u8"ods", u8"\uf1c3 "},
								   std::pair {u8"odt", u8"\uf72c "},
								   std::pair {u8"pdf", u8"\uf1c1 "},
								   std::pair {u8"pps", u8"\uf1c4 "},
								   std::pair {u8"ppt", u8"\uf1c4 "},
								   std::pair {u8"pptx", u8"\uf1c4 "},
								   std::pair {u8"rtf", u8"\uf15c "},
								   std::pair {u8"tex", u8"\ue612 "},
								   std::pair {u8"txt", u8"\uf0f6 "},
								   std::pair {u8"xls", u8"\uf1c3 "},
								   std::pair {u8"xlsx", u8"\uf1c3 "},
								   // Archive & Compress
								   std::pair {u8"7z", u8"\uf1c6 "},
								   std::pair {u8"bz2", u8"\uf066 "},
								   std::pair {u8"bzip", u8"\uf066 "},
								   std::pair {u8"bzip2", u8"\uf066 "},
								   std::pair {u8"deb", u8"\uf306 "},
								   std::pair {u8"gz", u8"\uf1c6 "},
								   std::pair {u8"xz", u8"\uf1c6 "},
								   std::pair {u8"pkg", u8"\uf487 "},
								   std::pair {u8"rar", u8"\ufac3"},
								   std::pair {u8"rpm", u8"\uf316 "},
								   std::pair {u8"tar", u8"\uf1c6 "},
								   std::pair {u8"tgz", u8"\uf1c6 "},
								   std::pair {u8"z", u8"\uf1c6 "},
								   std::pair {u8"zip", u8"\uf1c6 "},
								   // Comics
								   std::pair {u8"Comics", u8"\uf02d "},
								   std::pair {u8"cbr", u8"\ufc98 "},
								   std::pair {u8"cbz", u8"\ufc98 "},
								   // Git
								   std::pair {u8"FETCH_HEAD", u8"\ue708 "},
								   std::pair {u8"HEAD", u8"\ue708 "},
								   std::pair {u8"ORIG_HEAD", u8"\ue708 "},
								   std::pair {u8"branches", u8"\ue725 "},
								   std::pair {u8"git", u8"\ue5fb "},
								   std::pair {u8"gitconfig", u8"\uf1d3 "},
								   std::pair {u8"gitmodules", u8"\uf1d3 "},
								   std::pair {u8"gitignore", u8"\uf1d3 "},
								   std::pair {u8"hooks", u8"\ufbe0 "},
								   // Games
								   std::pair {u8"Minecraft", u8"\uf872 "},
								   std::pair {u8"Team Fortress 2", u8"\uf1b7 "},
								   std::pair {u8"minecraft", u8"\uf872 "},
								   std::pair {u8"steam", u8"\uf9d2"}};

static constexpr std::u8string_view default_file_icon {u8"\uf15b "};
static constexpr std::u8string_view default_directory_icon {u8"\ue5fe "};

inline std::u8string_view get_ext_from_filename(const std::u8string_view filename)
{
	const auto last_dot = filename.find_last_of('.');
	if(last_dot == filename.npos)
		return filename;

	return filename.substr(last_dot + 1ULL);
}

inline std::optional<std::u8string_view> get_icon_from_ext(const std::u8string_view ext)
{
	for(auto&& pair: icons)
		if(pair.first == ext)
			return pair.second;

	return std::nullopt;
}
